"""Real-photo sheet dataset: ml/data/sheet/ layout and manifest loader.

Layout (all paths relative to backend/ml/data/sheet/):
    photos/       your JPG/PNG captures of lenses on the printed sheet
    masks/        PNG lens masks, one per photo (auto-generated first, verified after)
    manifest.csv  filename,lens_id,width_a_mm,height_b_mm,nasal,notes

Manifest example:
    photo_001.jpg,lens_A,52.30,31.10,nasal_right,overhead daylight

width_a_mm / height_b_mm are caliper ground truth in boxing orientation
(A = horizontal in the sheet plane, long edge of the 100 mm ruler).
masks/ PNGs are white lens interior on black, same pixel size as the photo.
They are generated by scripts (never hand-drawn): first pass by the current
pipeline on the sheet-rectified image, then corrected where the overlay disagrees.
"""
from __future__ import annotations

import csv
import pathlib

import numpy as np
from PIL import Image

DATA_DIR = pathlib.Path(__file__).with_name("data") / "sheet"

COLUMNS = ("filename", "lens_id", "width_a_mm", "height_b_mm", "nasal", "notes")


def load_manifest(manifest: pathlib.Path | None = None) -> list[dict]:
    path = manifest or (DATA_DIR / "manifest.csv")
    if not path.exists():
        return []
    with open(path, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    records = []
    for row in rows:
        records.append({
            "filename": row["filename"],
            "lens_id": row["lens_id"],
            "width_a_mm": float(row["width_a_mm"]),
            "height_b_mm": float(row["height_b_mm"]),
            "nasal": row.get("nasal", ""),
            "notes": row.get("notes", ""),
        })
    return records


def load_pair(record: dict) -> tuple[np.ndarray, np.ndarray]:
    img = np.asarray(Image.open(DATA_DIR / "photos" / record["filename"]).convert("RGB"))
    mask = np.asarray(Image.open(DATA_DIR / "masks" / (pathlib.Path(record["filename"]).stem + ".png")).convert("L"))
    mask = (mask > 127).astype(np.uint8) * 255
    assert img.shape[:2] == mask.shape, f"mask size mismatch for {record['filename']}"
    return img, mask
